### ISSUE TITLE
What is the size of input image during inference?

### ISSUE THREAD

**Issue by DangDinhQuocTrung** [TobiasGruening/ARU-Net#10]
Is there a fixed size that an image is resized to?
Or, the image is resized according to some ratio?

**Comment by TobiasGruening** [comment]
Hey,
none of those.
There are parameter: scale_min=0.2, scale_max=0.5, scale_val=0.33
sclae_min and scale_max is the range in which the sampling factor is sampled from during training.
scale_val is the fixed scaling factor for the image in inference.

Hence, the images can be of arbitrary dimensions, but a sampled by a certain factor (to be in a reasonable range). Of course, this factor depends on the resolution of your images.

Kind regards,
Tobias
