### ISSUE TITLE
How to input a batch of images during inference rather than just one image

### ISSUE THREAD

**Issue by jewelc92** [TobiasGruening/ARU-Net#11]
I want to accelerate the inference process by inputting a batch of images, I concatenate several images and feed them to the variable 'x' in def inference in inference_pb.py, but the results are wrong while inputting only one image can get the right results.

**Comment by TobiasGruening** [comment]
You solved it on your own? I wanna have a look on it this afternoon.

**Comment by jewelc92** [comment]
> You solved it on your own? I wanna have a look on it this afternoon.

Yes, I just feed a batch of images to x, but speed didn't get faster
