### ISSUE TITLE
Dataset about 2017cBAD test xml groundtruth

### ISSUE THREAD

**Issue by lius0-0** [TobiasGruening/ARU-Net#13]
I can't get 2017cBAD dataset about test,where can I get the xml of test dataset's groundtruth?Could you give me a hand.Track A [Simple Documents]  and Track B [Complex Documents].
thank you a lot

**Comment by TobiasGruening** [comment]
They should be included here:

https://zenodo.org/record/835441#.XOT8IN9fikA

**Comment by lius0-0** [comment]
thanks a lot


------------------ 原始邮件 ------------------
发件人: "TobiasGruening"<notifications@github.com>;
发送时间: 2019年5月22日(星期三) 下午3:37
收件人: "TobiasGruening/ARU-Net"<ARU-Net@noreply.github.com>;
抄送: "青子莲"<739410424@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [TobiasGruening/ARU-Net] Dataset about 2017cBAD test xmlgroundtruth (#13)




They should be included here:
 
https://zenodo.org/record/835441#.XOT8IN9fikA
