### ISSUE TITLE
Train from the demo model

### ISSUE THREAD

**Issue by Dragule** [TobiasGruening/ARU-Net#14]
Hello,

I would like to train ARU-Net on printed text but keeping what have been done on handwriting.
Is there anywhere I can find the checkpoints created during the training of the model100_ema.pb demo file ?

Thanks !

**Comment by TobiasGruening** [comment]
No, I'm sorry. I just had a look, but did not found them anymore.

I would suggest that you just train it on your own. Since, the dataset is open source it should bemanageable.

Kind regards & Sorry,
Tobias
