### ISSUE TITLE
can you publish code of the second stage in the paper?

### ISSUE THREAD

**Issue by kalupiu** [TobiasGruening/ARU-Net#16]
The second part is the most valuable part in the paper, can you publish the corresponded code as well so we can easily get started? Thanks a lot

**Comment by TobiasGruening** [comment]
Hey,

no sorry unfortunately this is not possible due to licensing issues with underlying libs.

Kind regards,
Tobias

**Comment by imagine5am** [comment]
You can get baseline coordinates using this [repository](https://github.com/imagine5am/ARU-Net) in the form of PAGE-XML.
