### ISSUE TITLE
How not to use weight on cbad dataset

### ISSUE THREAD

**Issue by elyamanyahmed95** [TobiasGruening/ARU-Net#17]
I am trying to use your architecture on the cbad dataset 2017. 

With crossentropyloss I need weights to overcome the unbalanced classes between foreground and background. Neither in the paper or the code weights are mentioned. How did you overcome this problem?

Also The cbad dataset has around 256 images for training but you trained your model on 1024/ epoch. I also do not know how to get those 1024 images.

Thanks.

**Comment by TobiasGruening** [comment]
Hey,

in our experiments, this problem wasn't a problem. We experimented with weighted classes, but these experiments didn't improved the results. These unbalanced classed were not a problem.

For us, the number of samples per epoch is NOT related to the number of training samples. I.e. an epoch with 1024 samples for a training set of 256 images is totally fine (each image is shown 4 times).

Kind regards,
Tobias

**Comment by elyamanyahmed95** [comment]
Hi Tobias ,
Thanks alot for replying...
Yeah that what was interesting about the code, in the paper you achieved very good results for cbad 2017 dataset. When I tried it, there is a class imbalance, of about 1 to 10. How is this handled in the code? 
Kind Regards,
Ahmed

**Comment by TobiasGruening** [comment]
Hey,
you are welcome.
As I mentioned in my reply we just trained with these unbalanced classes and it didn't worsened the training. However, in 
pix_lab/training/cost.py
is the possibility to work with class weights.
You can specify them via the "class_weights" flag.
In our cases, this didn't improved the results.

Kind regards,
Tobias
