### ISSUE TITLE
demo weights and training times

### ISSUE THREAD

**Issue by xen0f0n** [TobiasGruening/ARU-Net#18]
Do the demo weights come from training  only on Track A, only on Track B, or on both tracks? 

Right now, training on Track A using 1024 samples/epoch takes ~20min/epoch and training on both training sets of Track A and Track B for the same number of samples takes ~40 min/epoch (possibly because Track B images are larger) (Nvidia GTX 1080).
Given that on the paper it's stated that it takes 3h to 24h to train the ARU-Net, do these times make sense or am I doing something wrong, (because even for 20min/epoch it will take much longer than 24h to reach epoch 250).

**Comment by olfaa** [comment]
Please how to show or plot the number trainable parameters in terminal screen.

Thank in advance

**Comment by TobiasGruening** [comment]
Hi,
if I remember right, the demo weights are the result of a training on both tracks.

Do you use the original image resolution to train, or do you downscale the images?

Kind regards,
Tobias

**Comment by olfaa** [comment]
Thank you for your response.
I try to train your model from scratch using 'aru' model and Bozen dataset. But in the test step when I plot the prediction result nothing obtained (black image).  I think that I didn't transform the model well using export_ckpt.py file. So I have question : after the model finishes the training stage, do we use export_ckpt.py  file to transform the model into model.pb format. If no, can you tell me please how we can do it knowing that the model converges in the traning stage ( look at info.log file)
Really thank you in advance.    Le vendredi 17 juillet 2020 à 09:17:14 UTC+1, TobiasGruening <notifications@github.com> a écrit :  
 
 


Hi,
if I remember right, the demo weights are the result of a training on both tracks.

Do you use the original image resolution to train, or do you downscale the images?

Kind regards,
Tobias

**Comment by olfaa** [comment]
I try to train your model from scratch using 'aru' model and Bozen dataset. But in the test step when I plot the prediction result nothing obtained (black image).  I think that I didn't transform the model well using export_ckpt.py file. So I have question : after the model finishes the training stage, do we use export_ckpt.py  file to transform the model into model.pb format. If no, can you tell me please how we can do it knowing that the model converges in the traning stage 

Really thank you in advance.

**Comment by AnuragSahu** [comment]
Thanks @olfaa the export_ckpt.py was never mentioned anywhere and I wasted a lot of time figuring it out. You suggestion works.
