### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by olfaa** [TobiasGruening/ARU-Net#19]
Please can you send me the Bozen dataset with its associated ground truth (ground truth of class separator and baseline) that used in your paper "A Two-Stage Method for Text Line Detection in Historical Documents".

Please , how we can show the number of trainable parameters architecture in terminal screen using your ARU-Net model.

Thank you in advance for your help.

**Comment by TobiasGruening** [comment]
Hi,

you'll find the Bozen Dataset her: https://zenodo.org/record/218236#.XszWZB9fiV4
(GT as page XML). I'll have a look, whether I can send you the respective pixel level GT. 

The possibility to get the trainable parameter is not directly included, but you can include a few lines of code to get a workaround, e.g., have a look at
https://stackoverflow.com/questions/38160940/how-to-count-total-number-of-trainable-parameters-in-a-tensorflow-model

**Comment by xinxin664** [comment]
> Please can you send me the Bozen dataset with its associated ground truth (ground truth of class separator and baseline) that used in your paper "A Two-Stage Method for Text Line Detection in Historical Documents".
> 
> Please , how we can show the number of trainable parameters architecture in terminal screen using your ARU-Net model.
> 
> Thank you in advance for your help.

Have you got pixel level dataset,and have you mastered how to generate pixel level dataset? Please share with me.
Thank you in advance for your help.

**Comment by TobiasGruening** [comment]
I just uploaded the pixel GT. Have a look at demo_images...
