### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by xinxin664** [TobiasGruening/ARU-Net#20]
Please can you send me the Bozen dataset with its associated ground truth (ground truth of class separator and baseline) that used in your paper "A Two-Stage Method for Text Line Detection in Historical Documents".

Please ,I want to know how to get the respective pixel level GT.

Thank you in advance for your help.

**Comment by TobiasGruening** [comment]
I just uploaded the pixel GT. Have a look at demo_images...
