### ISSUE TITLE
demo model fail with low resolution

### ISSUE THREAD

**Issue by lynx97** [TobiasGruening/ARU-Net#21]
I try to inference with document image using pretrained model. With high resolution images, it works fine. But some documents with lower resolution, i.e: 700x800 it 's not working well.

**Comment by TobiasGruening** [comment]
Hi Lynx,
per default the images are downscaled: `scale=0.33` have a look at util.inference_pb maybe adapting this for your low resolution images is a good idea.
Kind regards,
Tobias

**Comment by lynx97** [comment]
> Hi Lynx,
> per default the images are downscaled: `scale=0.33` have a look at util.inference_pb maybe adapting this for your low resolution images is a good idea.
> Kind regards,
> Tobias

Thanks, It works.
