### ISSUE TITLE
input image size

### ISSUE THREAD

**Issue by Mchapariniya** [TobiasGruening/ARU-Net#24]
Hello and thanks for your great work. I'm working on scanned Persian documents and I want to extract their lines. In many images ARUnet gives good results but for very small and very large images it fails! Is there any restrictions on the size of the input image?

**Comment by TobiasGruening** [comment]
Hi,
there is no 'hard' restriction. However, the model was trained on data in a certain resolution space. However, it should be invariant to moderate changes in the resolution. What do you mean with very small and very large? If you say 'fails', you mean the result looks bad or are there errors and no result is computed?

**Comment by Mchapariniya** [comment]
![image](https://user-images.githubusercontent.com/53124368/137687408-fa27a0a3-f6e6-401e-87a6-e2eac8786552.png)
![Capture1](https://user-images.githubusercontent.com/53124368/137687472-d7de68ca-7a25-4f6a-a14a-c4cd83f19ef1.PNG)
For the two images above, the network results and the size of the input image are shown. The network could not find any line for these images. In fact, it has not produced any results.

**Comment by TobiasGruening** [comment]
To meet the typically image size expectation here:
https://github.com/TobiasGruening/ARU-Net/blob/master/pix_lab/main/validate_pb.py#L14
(similar in the validate script)
the input is downscaled by a factor of 3. Would you mind to try `scale_val=1.0` instead of `scale_val=0.33`?

**Comment by zhubenfu** [comment]
Zhu Ben-FuCEOTel: +86 150-5813-3936weixin：portumoE-mail: ***@***.*** 前后相机同时拍 http://www.feelu.cn
