### ISSUE TITLE
[Get text]

### ISSUE THREAD

**Issue by cuonghv0298** [TobiasGruening/ARU-Net#25]
Hi sir, 
Your project is so sexy to me. And I hope to apply this nice contribution to detection text. I mean I detected my line text but I need the separation in this line. I try to find contours in your output and then matching them with box line but It's hard to do. Can you give me some idea?

**Comment by zhubenfu** [comment]
Zhu Ben-FuCEOTel: +86 150-5813-3936weixin：portumoE-mail: ***@***.*** 前后相机同时拍 http://www.feelu.cn
