### ISSUE TITLE
Generating the pixel ground truth images [Converting labeled layout files into ground-truth]

### ISSUE THREAD

**Issue by ghost** [TobiasGruening/ARU-Net#3]
@TobiasGruening As shown in your published paper, that we need the **`original images`** along with their **`pixel ground truth`** in-order to train.
The bounding-boxes can be easily annotated into a PAGE XML, but my question is:

How to convert the PAGE XML into pixel ground truth images?
![121313-compressed-86](https://user-images.githubusercontent.com/33478216/45318711-631d4180-b546-11e8-8041-36040ce703d9.jpg)

**Comment by xinxin664** [comment]
> @TobiasGruening As shown in your published paper, that we need the **`original images`** along with their **`pixel ground truth`** in-order to train.
> The bounding-boxes can be easily annotated into a PAGE XML, but my question is:
> 
> How to convert the PAGE XML into pixel ground truth images?
> ![121313-compressed-86](https://user-images.githubusercontent.com/33478216/45318711-631d4180-b546-11e8-8041-36040ce703d9.jpg)

Have you solved the problem?Can you tell me how you solved it?Thank you very much!
