### ISSUE TITLE
train_aru.py path problem

### ISSUE THREAD

**Issue by jupinter** [TobiasGruening/ARU-Net#6]
perhaps move ARU-Net/pix_lab/main/train_aru.py to ARU-Net/train_aru.py  is better. Otherwise lib problems may rise

**Comment by jupinter** [comment]
I ran through the code using my own training data. It is text line, X.jpg contains gray image, X_GT0.jpg contains background information.  X_GT1.jpg contains baseline information.  X_GT2.jpg contains the separator information.  For each position the sum is one. But when test the module, all pixels are predicted as separator.  Could you supply a sample image so that I can do more analysis?

**Comment by TobiasGruening** [comment]
Hi Jupinter,
that sounds strange.
Do you mean a sample image with corresponding GT information?

Kind regards,
Tobias

**Comment by jupinter** [comment]
Hi, TobiasGruening
I think I got the answer
    <aTgt = np.where(aTgt > 64, 1.0, 0.0)>
Thanks a lot for replying.

**Comment by TobiasGruening** [comment]
Don't hesitate if you have further questions.

You should think about rearranging the order of your GT images. Since, the first channel is of "highest" importance, it yould be meaningful to put the background class at the end, i.e., X_GT2.jpg

Kind reagrds,
Tobias
