### ISSUE TITLE
Ground Truth images

### ISSUE THREAD

**Issue by alperdemir03** [TobiasGruening/ARU-Net#7]
Hello, I want to train network with another dataset.

I read the paper but can't get some parts. Can you please explain how can I generate pixel ground truth.
I need some example of ground truth file (X_GT1.jpg,X_GT2.jpg, X_GT3.jpg).  If I had an example of Ground truth data, I could generate others.

Thank you

**Comment by TobiasGruening** [comment]
@alperdemir03 
You can find a sample training date under demo_iamges/demo_traindata

Kind regards,
Tobias
