### ISSUE TITLE
Number of training images necessary

### ISSUE THREAD

**Issue by apirrone** [TobiasGruening/ARU-Net#8]
Hello, 

I wonder how many images (and their corresponding ground truth images) you would consider enough for training your network ?

Thanks !

**Comment by TobiasGruening** [comment]
Hey,
this definitively depends on the homogenity of the image distribution you are interested in.
E.g., if you are interested in newspaper articles of a certain newspaper, or handwritten council protocols 
which are quite homogeneous, I would expect that 50-100 images are enough.
If your scenario is diverse, like modern forms, mixed with..., mixed with... you will need 1000+ images.

Kind regards,
Tobias

**Comment by apirrone** [comment]
Ok, thank you very much for the quick reply !

My image distribution is quite homogeneous, and generating 50-100 ground truth images manually is manageable for me, so I'll be sure to try it out !

**Comment by TobiasGruening** [comment]
Cool. :)
Have fun, and ask if you have any problems.

I'll close this for the moment.
