### ISSUE TITLE
Train and validation loss are always 0.0000

### ISSUE THREAD

**Issue by apirrone** [TobiasGruening/ARU-Net#9]
Hi,

I created some ground truth to try your network, and after tweaking some things, I'm able to launch the training and it goes without errors. However, the averge loss for training and validation is always 0 ... 

![capture d ecran de 2019-01-22 11-10-14](https://user-images.githubusercontent.com/6552564/51528160-55ea5a80-1e36-11e9-83d6-f3b8fbb9e824.png)

Actually, the "raw" loss returned by sess.run(...) is 0. 

Do you have an idea of what could cause that ?

Thanks !

**Comment by TobiasGruening** [comment]
Hey,

can you maybe send my one of your training samples per mail, that I can have a closer look?
Or are they private?

**Comment by apirrone** [comment]
Unfortunately I work on data that is confidential right now (historical documents which have not been published yet) so I can't send you one of my training samples. But here is a Google found image that is basically what I'm working on : 

![capture d ecran de 2019-01-23 10-41-21](https://user-images.githubusercontent.com/6552564/51597408-77f9e080-1efb-11e9-8f52-de9d5abe868c.png)

And based on the examples ground truth images you gave, I would annotate this image like this : 

![gt](https://user-images.githubusercontent.com/6552564/51597681-19813200-1efc-11e9-8bc5-b6834d75dd62.png)

**Comment by TobiasGruening** [comment]
So, you are training the network in a 2 class fashion?
Meaning, 1 class predicting the baselines and the second channel predicting 
the NOT baseline without the separator class?

Hence, your groundtruth consists of the image above and its inverted version?
If you confirm this, I can try to run the training with the image you provided above
and will see what happens :)

Kind regards,
Tobias

**Comment by apirrone** [comment]
I'm trying to train the network in a 1 class fashion, with just the second image as ground truth.

I didn't read the papers yet, I'm trying to figure out if your solution could be of use with my problem, so it is absolutely possible that I misunderstood some things and did stupid things with the code :)

**Comment by TobiasGruening** [comment]
Hehe, I am convinced, that we can fix it together.
I'll have a look in the afternooon.

**Comment by apirrone** [comment]
Cool thanks !

**Comment by TobiasGruening** [comment]
Hey,

I made some changes in the data load and process routine. Please pull them.
Furthermore a few hints:

If you have a look at the train_aru.py function there is the snippet:

    img_channels = 4
    # Number of output classes
    n_class = 2
    kwargs_dat = dict(batchsize_tr=1, scale_min=0.66, scale_max=1.0, scale_val=0.75, affine_tr=True,
                      one_hot_encoding=True)

img_channels has to match the number of channels in your input image, for instance you example above has 4 channels, if you use a gray-scale image, which is saved in an approriate format, it should have 1 channel. Nevertheless, the model has to know how much channels the input has, Therefore, you have to provide the correct number. If you provide a wrong number, the program will raise an error, and you will notice, e.g. 'ValueError: Cannot feed value of shape (1, 282, 147, 4) for Tensor u'inImg:0', which has shape '(?, ?, ?, 2)'

Furthermore, if you are interested in 1 class (the baselines), you have set n_class=2 since, there has to be a clutter class. This clutter class is active if all classes you are interested in are not active...

Finally, take care, that scale_min=0.2, scale_max=0.5, scale_val=0.33 are in a meaningful range.
The images are randomly sampled in training in a range between 0.2 and 0.5 in this case...
For images, in a very poor resolution 0.66 and 1.0 are a better choice...

Let me know, if you could make any progress.

Kind regards,
Tobias

**Comment by apirrone** [comment]
Great, I'll try all this tomorrow and l'll let you know !

**Comment by apirrone** [comment]
Pulling your changes and changing n_class from 1 to 2 solved the problem !

I'll let it train for a while and report back on the results :)

Thank you very much !

**Comment by apirrone** [comment]
I must say, I didn't expect such good results with this few training examples !

It's not perfect, but the loss didn't go very low during the 100 training epoch, and I can definitely improve my training dataset :) 

Thanks a lot for your help, I'm going to read your papers and dig into the code now!

Is it okay if I open an issue if I have a question ? Or do you prefer another way of communicating ?

**Comment by TobiasGruening** [comment]
Nice to hear :)
In the end, I guess you will be able to improve your results by improving the training set as well as by 
tuning the hyperparameters a little bit.
Especially, the image scaling, as well as data augmentation parameters.

Feel free to open issues, if you have any questions.

Kind regards,
Tobias

**Comment by sahumson** [comment]
Hi Tobias
I tried your training demotraindata GT files to test the training code 

I facing this issue 
CUDA_VISIBLE_DEVICES=0 python pix_lab/main/train_aru.py
Model Type: ru
Traceback (most recent call last):
  File "pix_lab/main/train_aru.py", line 48, in <module>
    run(path_list_train,path_list_val,output_folder,None)
  File "pix_lab/main/train_aru.py", line 36, in run
    model = ARUnet(img_channels, n_class, model_kwargs=model_kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/pix_lab/models/aru_net.py", line 237, in __init__
    self.num_scales)
  File "/opt/anaconda3/lib/python3.6/site-packages/pix_lab/models/aru_net.py", line 160, in create_aru_net
    featRoot, filter_size, pool_size, activation)
  File "/opt/anaconda3/lib/python3.6/site-packages/pix_lab/models/aru_net.py", line 58, in detCNN
    actFeatNum], activation=activation)
  File "/opt/anaconda3/lib/python3.6/site-packages/pix_lab/util/layers.py", line 48, in conv2d_bn_lrn_drop
    initializer=tf.random_normal_initializer(stddev=stddev))
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 664, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable featMapG/unet_down_layer/convR_aRe/weights already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/opt/anaconda3/lib/python3.6/site-packages/pix_lab/util/layers.py", line 48, in conv2d_bn_lrn_drop
    initializer=tf.random_normal_initializer(stddev=stddev))
  File "/opt/anaconda3/lib/python3.6/site-packages/pix_lab/models/aru_net.py", line 58, in detCNN
    actFeatNum], activation=activation)
  File "/opt/anaconda3/lib/python3.6/site-packages/pix_lab/models/aru_net.py", line 160, in create_aru_net
    featRoot, filter_size, pool_size, activation)

After this program is still running for a long time no iteration started

**Comment by TobiasGruening** [comment]
Hi!

Would you mind to test it with python 2.7 again?
I forgot to mention in the readme, that this repo is based on python2.7.
Sorry.

**Comment by sahumson** [comment]
Hi Tabias,
I tried with same code in python 2.7 in ubuntu, tensorflow version 1.13 and still I get the same error as above mentioned.

Let me know, if you need any more information.

**Comment by starride-irisa** [comment]
Hi !
I am getting the same issue. Have you managed to solve it ?

**Comment by TobiasGruening** [comment]
Hey,

it seemed to be a problem with the string handling in the variable scopes.
You can give it a try now.

Kind regards,
Tobias

**Comment by starride-irisa** [comment]
Hi,

Thanks a lot for your help ! It works perfectly now.

Kind regards,
Solène

**Comment by sahumson** [comment]
HI Tobias,

Now after the fix its working fine, thanks a lot for the help !!!. 

Regards,
sricharan

**Comment by xinxin664** [comment]
> Hi,
> 
> I created some ground truth to try your network, and after tweaking some things, I'm able to launch the training and it goes without errors. However, the averge loss for training and validation is always 0 ...
> 
> ![capture d ecran de 2019-01-22 11-10-14](https://user-images.githubusercontent.com/6552564/51528160-55ea5a80-1e36-11e9-83d6-f3b8fbb9e824.png)
> 
> Actually, the "raw" loss returned by sess.run(...) is 0.
> 
> Do you have an idea of what could cause that ?
> 
> Thanks !

Can you tell me how you created your ground truth?I also want to create some pixel ground truth.Thank you very much!
